### ISSUE TITLE
Ce qu'on a besoin pour le site web

### ISSUE THREAD

**Issue by greiko** [ageei/ageei.github.io#1]
* Ressources
* Informations sur l'executif
* Contacte
* Calendrier
* Info Lettre

**Comment by greiko** [comment]
* Ressources
* Informations sur l'executif
* Contacte
* Calendrier
* Info Lettre

**Comment by riclima** [comment]
SVP faire des _issues_ sur le développement du site internet sur ageei/site-internet.
